### ISSUE TITLE
How is this related to osmanip?

### ISSUE THREAD

**Issue by JustWhit3** [ohz10/console#1]
Hi @ohz10,

Don't want to be annoying, but just wanted to know how is this related to [osmanip](https://github.com/JustWhit3/osmanip), since you mentioned my library in the main README.md, but this repository seems to me a completely new implementation instead of a related improvement. Could you explain me? Thanks.

Cheers,
Gianluca.

**Comment by ohz10** [comment]
@JustWhit3 You are correct, this is a completely new implementation based off reference material found [here](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797) and [here](https://en.wikipedia.org/wiki/ANSI_escape_code). 

I use the "Related Projects" section of the README to reference other implementations in the same or similar problem domains, like a "related work" section in an academic paper. For another example of me using a "Related Projects" in a README, see one of my older projects [PluginFactory](https://github.com/ohz10/PluginFactory).

**Comment by JustWhit3** [comment]
My question is: why not sending a pull request to `osmanip` instead of creating an identical library? You could have improved an existing tool, used by other people, instead of creating a new one, which very very similar to mine.

I think that everyone should be free of creating whatever he/she wants, of course, but the fact is that, in my opinion, in this case too many features has a very similar structure to `osmanip`...

The fact that you at least putted `Related` on the main README it's ok, but I would expect you explain more how it is related, with something like "This is a re-implementation of an already existing library, called osmanip, with personal features and changes".

**Comment by ohz10** [comment]
> The fact that you at least putted Related on the main README it's ok, but I would expect you explain more how it is related

@JustWhit3 I think given a link to your project, most people will inherently understand these are separate projects and that there is no dependencies between them. I don't particularly see the need to pollute the README with disclaimers as you've suggested.

**Comment by ohz10** [comment]
> why not sending a pull request to `osmanip` instead of creating an identical library?

@JustWhit3 I agree the functionality between the two libraries achieves the same goals, albeit in with very different code structures, and there's little sense in having duplicates... other than me having some fun making "improvements".

Frankly, I would never post a PR to a project where I basically said "guys, I rewrote everything for you" =) that's not my M.O. I don't think a PR like that would be taken very seriously, nor should they.

However, I think this discussion is very healthy. And I welcome it, thank you for reaching out.

I would actually be open to working with you to improve `osmanip` by making some PRs against your project. I would like to mature what I've done here a bit, I don't think it's quite a complete thought yet. Then we can talk about what I've done that you like, and what you don't like and why.

**Comment by JustWhit3** [comment]
@ohz10 I am completely in agreement with you that a PR in which you completely rewrite something is not optimal and maybe (often) people would refuse it. In fact I was not talking about something like this. I was talking more about a "collaboration" in which you propose me an improvement or a new feature and then we could work on it together. See for example [this](https://github.com/JustWhit3/osmanip/discussions/21) discussion on `osmanip`, in which a guy is proposing me consistent modifications to the project and, after a few discussions, we found a way to proceed and improve the library structure itself, together. This is what I was talking about.

Of course it would be a pleasure for me to hear your ideas about `osmanip` improvements and find a common way to implement them in the project.

>  I would like to mature what I've done here a bit, I don't think it's quite a complete thought yet. Then we can talk about what I've done that you like, and what you don't like and why.

That's completely fine for me, of course! This is the kind of collaboration I was talking about. You are free to implement stuff as you want and then you can propose me changes (also consistent changes) which, if they are reasonable, I will warmly accept in my project. This is also a good way to be part of `osmanip` and help me and the other collaborators in growing that library, which is already used by different people. I understand that creating new stuff is always stimulating, but sometimes improving already existent projects may be a less waste of time, since you put effort in an already on going software and contribute to make it grow. 

It would be pleasured for me to have your help in the development of `osmanip`. Let me know when you are ready and we can freely open discussions about any kind of implementation you want to bring.
